### ISSUE TITLE
Example of real life problem for use case

### ISSUE THREAD

**Issue by deemuni** [smithjd/sql-pet#16]
Goals are explained clearly with 4 distinct use cases.  I think for me and for other beginning learners if a real-life scenario is explained it will make it easy for me to wrap my mind around it.  Obviously, for confidential reasons, we can use fake info but some problem that is typically experienced. 

Idea: This real-life scenario can be a guide in explaining the major concepts throughout the lesson.

**Comment by znmeb** [comment]
I have two projects I'm working on at the moment but only one involves Docker - https://github.com/znmeb/gtfs-collector

The plan is to deploy this as a private server collecting GTFS data and use R on the desktop via `dbplyr` to analyze the data. I expect to have the container running towards the end of this week; I want to start collecting data before the TriMet service changes happen next week. Most likely it'll be deployed on Digital Ocean - their $5/month `droplet` has 25 GB of SSD.

**Comment by smithjd** [comment]
Here's my original use case -- and a variant.

**Original:** set up an SQL DBMS on student's machines with moderately complicated data to learn how to deal with something similar to an organization's production- or data warehouse-environment.  Using Docker because students may or may not want to keep the DBMS around and it may involve lots of dependencies.

**Variant:** set up an SQL DBMS using Docker on a teacher's machine (or a spare).  Create an individual account on that DBMS for each student and send them a username/password that's good for use during the class.  All of that should be easy to do in R.  And the load from a class should probably not tax a good laptop too much.

**Comment by znmeb** [comment]
The original is a good use case for Docker - it means everyone has the identical version and other PostgreSQL configuration details! For the variant, you don't need Docker and it's an extra complexity you probably want to avoid.

**Comment by jimtyhurst** [comment]
I think @smithjd 's "Original" use case is really a _teaching goal_, not a real world _use case_. When I read @deemuni 's comment, I was thinking of some use stories like these:
* As a data scientist at DVDs R Us, I want to know the distribution of number of rentals per month per customer, so that the Marketing department can create incentives for customers in 3 segments: Frequent Renters, Average Renters, Infrequent Renters.
* As the Director of Sales, I want to see the total number of rentals per month for the past 6 months and I want to know how fast our customer base is growing/shrinking per month for the past 6 months.
* As the Director of Marketing, I want to know which categories of DVDs are the least popular, so that I can create a campaign to draw attention to rarely used inventory.
* As a shipping clerk, I want to add rental information when I fulfill a shipment order.
* etc.

I like @deemuni 's suggestion to use these real life situations to drive the exercises.

**Comment by znmeb** [comment]
@deemuni @smithjd Is this done? Can we close it?
