### ISSUE TITLE
.FATAL:  data directory "/var/lib/postgresql/data/pgdata" has wrong ownership

### ISSUE THREAD

**Issue by znmeb** [smithjd/sql-pet#7]
**Describe the bug**
Permission problems bringing up the PostgreSQL container

**To Reproduce**
1. Clone repo in Git Bash
2. Type `docker-compose.exe up`

**Expected behavior**
Container comes up with no errors

**Screenshots**
<img width="855" alt="capture" src="https://user-images.githubusercontent.com/4938/44621284-55826f00-a858-11e8-8299-a86b322edb4b.PNG">

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
- Docker for Windows Version 18.06.0-ce-win72 (19098)

**Additional context**

This is a known issue with Docker for Windows. It is flagged as `wontfix`. Solution is to eliminate mounting the host `./data` folder into the container. See https://github.com/docker/for-win/issues/39

**Comment by znmeb** [comment]
closing - pull request merged

**Comment by smithjd** [comment]
By removing the pg_data volume info from the YAML,  the dvdrental database does not persist after the `docker-compose stop` command is issued.  I think we have to go back to the YAML version that includes the **pg_data volume**:

https://github.com/smithjd/sql-pet/commit/4bc60b7534e5039e4d9cf8c94a7f8a0a00d0cd72

I am able to successfully install the dvdrental database as shown here:

https://github.com/smithjd/sql-pet/blob/master/src/3_install_dvdrental-in-postgres.md

But with the next file crashes because it doesn't find the dvdrental database:

https://github.com/smithjd/sql-pet/blob/master/src/4_test_dvdrental-database.md
